# Generated by Django 4.2.1 on 2023-06-21 14:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mi_campo', models.CharField(max_length=400, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]*$', 'Solo se permiten letras y números.')])),
            ],
        ),
    ]
