# Generated by Django 4.2 on 2023-06-19 21:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Tareas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='plazo_maximo',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
