# Generated by Django 4.2 on 2023-06-19 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tareas', '0002_tarea_plazo_maximo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='completado',
            field=models.BooleanField(default=False),
        ),
    ]
